version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - ./docker/database/init:/docker-entrypoint-initdb.d
      - ./docker/database/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=docker

  php-fpm:
    image: miamioh/php:7.3-fpm
    volumes:
      - .:/usr/share/nginx/app
      - ./docker/php/conf/php.ini:/usr/local/etc/php/php.ini:ro
    depends_on:
      - db
    working_dir: /usr/share/nginx/app

  nginx:
    image: miamioh/service:laravel-dev
    volumes:
      - .:/usr/share/nginx/app:ro
      - ./docker/logs/nginx:/var/log/nginx
    ports:
      - "${HTTP_HOST_PORT:-80}:${HTTP_PORT:-80}"
      - "${HTTPS_HOST_PORT:-443}:${HTTPS_PORT:-443}"
    depends_on:
      - php-fpm
